### ISSUE TITLE
Command Prediction for CommandBox

### ISSUE THREAD

**Issue by zameschua** [CS2103AUG2017-W15-B2/main#10]
## TODO
- [x] Implement basic functionality
- [x] Rename components to `CommandPrediction` for clarity (instead of `SearchPrediction` or `TextPrediction`
- [x] Add tests
- [x] Add more cases to support new commands that will be introduced up till V1.5
- [x] Update UG and DG

### Motivation
The command box is going to be the main way of navigating through CYNC.
It'd be great if we can make the text bar more powerful with text prediction / autocomplete.

### Description
I'ma do this in a few parts.
First part will only be involved with searching through commands,
Next part will be involved with making the find command more powerful

I'll try my best to touch only the UI component.

### UI Mockup
![image](https://user-images.githubusercontent.com/18271085/31314595-cf8395aa-ac36-11e7-9041-c440f3615049.png)

### Class Diagram
![image](https://user-images.githubusercontent.com/18271085/31314543-be81aeaa-ac35-11e7-8439-9fcbd17896dd.png)

**Comment by zameschua** [comment]
Basic implementation introduced in #12.
